<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find mini_cheetah_description)/xacro/transmission.xacro"/>

    <xacro:macro name="leg" params="name mirror mirror_dae front_hind front_hind_dae *origin">


<!-- //////////////////////hip//////////////////// -->
        <joint name="${name}_hip_joint" type="revolute">
        <!-- <joint name="${name}_hip_joint" type="continuous"> -->
            <xacro:insert_block name="origin"/>
            <parent link="trunk"/>
            <child link="${name}_hip"/>
            <axis xyz="1 0 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <xacro:if value="${(mirror_dae == False)}">
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${hip_min*PI/180.0}" upper="${hip_max*PI/180.0}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True)}">
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${-hip_max*PI/180.0}" upper="${-hip_min*PI/180.0}"/>
            </xacro:if>            
        </joint>

        <link name="${name}_hip">
            <visual>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                    <origin rpy="${PI} 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                    <origin rpy="0 ${PI} 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                    <origin rpy="${PI} ${PI} 0" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <mesh filename="package://mini_cheetah_description/meshes/hip.STL" scale="1 1 1"/>
                </geometry>
                <material name="gold"/>
            </visual>
            <collision>
                <!-- <origin rpy="${PI/2.0} 0 0" xyz="0 0 0"/> -->
                <!-- <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                    <origin rpy="${PI} 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                    <origin rpy="0 ${PI} 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                    <origin rpy="${PI} ${PI} 0" xyz="0 0 0"/>
                </xacro:if> -->
                <geometry>
                    <!-- <mesh filename="package://mini_cheetah_description/meshes/hip.STL" scale="1 1 1"/> -->
                    <box size="${hip_length} ${hip_width} ${hip_height}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${hip_com_x*front_hind} ${hip_com_y*mirror} ${hip_com_z}"/>
                <mass value="${hip_mass}"/>
                <inertia ixx="${(1/12) * hip_mass * (hip_width * hip_width + hip_height * hip_height)}" ixy="0.0" ixz="0.0"
                         iyy="${(1/12) * hip_mass * (hip_length * hip_length + hip_height * hip_height)}" iyz="0.0"
                         izz="${(1/12) * hip_mass * (hip_length * hip_length + hip_width * hip_width)}" />     
            </inertial>
        </link>

       
<!-- //////////////////////thigh//////////////////// -->

        <joint name="${name}_thigh_joint" type="revolute">
        <!-- <joint name="${name}_thigh_joint" type="continuous"> -->
            <origin rpy="0 0 0" xyz="0 ${-thigh_offset*mirror} 0"/>
            <parent link="${name}_hip"/>
            <child link="${name}_thigh"/>
            <axis xyz="0 -1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}" lower="${thigh_min*PI/180.0}" upper="${thigh_max*PI/180.0}"/>
        </joint>

        <link name="${name}_thigh">      
            <visual>
                <xacro:if value="${mirror_dae == True}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>                 
                </xacro:if>
                <xacro:if value="${mirror_dae == False}">
                    <origin rpy="${PI} ${PI} 0" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <mesh filename="package://mini_cheetah_description/meshes/thigh.STL" scale="1 1 1"/>
                </geometry>
                <material name="white_blue"/>
            </visual>
            <collision>
                 <!-- <xacro:if value="${mirror_dae == True}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>                 
                </xacro:if>
                <xacro:if value="${mirror_dae == False}">
                    <origin rpy="${PI} ${PI} 0" xyz="0 0 0"/>
                </xacro:if> -->
                <origin rpy="0 0 0" xyz="0 0 -${thigh_height / 2}"/>
                <geometry>
                    <box size="${thigh_length} ${thigh_width} ${thigh_height}"/>
                    <!-- <mesh filename="package://mini_cheetah_description/meshes/thigh.STL" scale="1 1 1"/> -->
                </geometry>    
                <material name="white_blue"/>  
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${thigh_com_x} ${thigh_com_y*mirror} ${thigh_com_z}"/>
                <mass value="${thigh_mass}"/>
                <inertia ixx="${(1/12) * thigh_mass * (thigh_width * thigh_width + thigh_height * thigh_height)}" ixy="0.0" ixz="0.0"
                         iyy="${(1/12) * thigh_mass * (thigh_length * thigh_length + thigh_height * thigh_height)}" iyz="0.0"
                         izz="${(1/12) * thigh_mass * (thigh_length * thigh_length + thigh_width * thigh_width)}" />     
            </inertial>
        </link>

<!-- //////////////////////calf//////////////////// -->
        <joint name="${name}_calf_joint" type="revolute">
        <!-- <joint name="${name}_calf_joint" type="continuous"> -->
            <origin rpy="0 0 0" xyz="0 0 -0.2115"/>
            <parent link="${name}_thigh"/>
            <child link="${name}_calf"/>
            <axis xyz="0 -1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <!-- <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}" lower="${calf_min*PI/180.0}" upper="${calf_max*PI/180.0}"/> -->
            <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}" lower="-${PI}" upper="${PI}"/>
        </joint>

        <link name="${name}_calf">
            <visual>           
                <origin rpy="0 0 0" xyz="0.0 0.009 0.0" />
                <geometry>
                    <mesh filename="package://mini_cheetah_description/meshes/calf.STL" scale="1 1 1"/>
                </geometry>
                <material name="white_blue"/>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0.0 0.0 -${calf_height / 2}" />
                <geometry>
                    <box size="${calf_length} ${calf_width} ${calf_height}"/>
                    <!-- <mesh filename="package://mini_cheetah_description/meshes/calf.STL" scale="1 1 1"/> -->
                </geometry>      
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${calf_com_x} ${calf_com_y} ${calf_com_z}"/>
                <mass value="${calf_mass}"/>
                <inertia ixx="${(1/12) * calf_mass * (calf_width * calf_width + calf_height * calf_height)}" ixy="0.0" ixz="0.0"
                         iyy="${(1/12) * calf_mass * (calf_length * calf_length + calf_height * calf_height)}" iyz="0.0"
                         izz="${(1/12) * calf_mass * (calf_length * calf_length + calf_width * calf_width)}" />    
            </inertial>
        </link>


<!-- //////////////////////foot//////////////////// -->
        <joint name="${name}_foot_fixed" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 -0.23039"/>     
            <parent link="${name}_calf"/>
            <child link="${name}_foot"/>
        </joint>

        <link name="${name}_foot">
            <visual>
                <origin rpy="0 0 0" xyz="0 0.018 0.02"/>
                <geometry>
                     <mesh filename="package://mini_cheetah_description/meshes/foot.STL" scale="1 1 1"/>
                </geometry>
                <material name="white_black"/>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0.0 0.025"/>
                <geometry>
                    <!-- <mesh filename="package://mini_cheetah_description/meshes/foot.STL" scale="1 1 1"/> -->
                    <sphere radius="0.025"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${foot_com_x} ${foot_com_y} ${foot_com_z}"/>
                <mass value="${foot_mass}"/>
                <inertia ixx="${(2/5) * foot_mass * ( (foot_radius) * (foot_radius) )}" ixy="0.0" ixz="0.0"
                         iyy="${(2/5) * foot_mass * ( (foot_radius) * (foot_radius) )}" iyz="0.0"
                         izz="${(2/5) * foot_mass * ( (foot_radius) * (foot_radius) )}" />          
            </inertial>
        </link>

        <xacro:leg_transmission name="${name}"/>
    </xacro:macro>
</robot>
